fix: consistent error logging with stderr and offending cmd
mykso/myks pull request #143
Opened 2023-12-10 10:55 UTC by fritzduchardt

2023-12-10 20:15 UTC, kbudde requested changes
Hey @fritzduchardt, I like it but I think you can improve it even more.

2023-12-10 20:15 UTC, kbudde commented on internal/myks/application.go
> +	return runCmd(cmd, stdin, args, func(cmd string, err error, stderr string, args []string) {
```suggestion
	return runCmd(cmd, stdin, args, logCmd(output))
```

2023-12-17 10:46 UTC, fritzduchardt commented on internal/myks/application.go
> +		cmd = msgRunCmd(purpose, cmd, args)
So true, done

2023-12-21 00:34 UTC, Zebradil approved these changes

2023-12-21 00:34 UTC, merged