Execute helm dependency build
mykso/myks pull request #154
Opened 2023-12-23 19:43 UTC by fritzduchardt

Closes #146 

Can be activated in app-data.ytt.yaml with:

```
helm:
  buildDependencies: true
```

2023-12-23 23:47 UTC, Zebradil requested changes
I dug around a little and bumped into https://github.com/helm/helm/issues/7214.

Can we just use `helm template --dependency-update` instead of manually downloading dependencies?

2023-12-23 23:47 UTC, Zebradil commented on internal/myks/render.go
> +	resourceValues, err := a.mergeValuesYaml(initStepName, a.expandTempPath(valuesFileName))
Why is this changed?

2023-12-23 23:47 UTC, Zebradil commented on internal/myks/util_test.go
> +		{"nginx", args{"https://helm.nginx.com/stable"}, "helm.nginx.com"},
A slug should include more parts of a registry URL than just a domain name.
Otherwise, the current logic will fail if a chart has dependencies in two different registries with the same domain name. For example:

- https://charts.helm.sh/stable
- https://charts.helm.sh/beta

2023-12-23 23:47 UTC, Zebradil commented on internal/myks/application.go
> +}
Where is this used? It seems that it's some leftovers from past ideas (calculating a namespace for the local apply, I suppose). I suggest leaving only the Helm part in this PR.

2023-12-23 23:54 UTC, Zebradil commented
The flag seems to work perfectly. Here is how I tested:

```shell
cd $(mktemp -d)
cat <<EOF > Chart.yaml
apiVersion: v2
name: webserver
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.16.0
dependencies:
  - name: mysql
    version: 9.3.4
    repository: https://charts.bitnami.com/bitnami
EOF
helm template . --dependency-update
```

Result:

![image](https://github.com/mykso/myks/assets/1475583/34070187-0dbb-48bb-8faa-8db736c469d5)

2023-12-26 06:12 UTC, fritzduchardt commented
> I dug around a little and bumped into [helm/helm#7214](https://github.com/helm/helm/issues/7214).
> 
> Can we just use `helm template --dependency-update` instead of manually downloading dependencies?

This is a pretty good find I was not ware of. Nevertheless, dependency build would still be my preference, since it respects the Chart.lock file. Dependency update would always renegotiate dependencies and lose the ability to pin Chart dependencies.

2023-12-26 06:13 UTC, fritzduchardt commented on internal/myks/render.go
> +	resourceValues, err := a.mergeValuesYaml(initStepName, a.expandTempPath(valuesFileName))
Accidental, good spot

2023-12-26 06:16 UTC, fritzduchardt commented on internal/myks/util_test.go
> +		{"nginx", args{"https://helm.nginx.com/stable"}, "helm.nginx.com"},
Good point - I have left the path in place and replace / with -

2023-12-26 06:21 UTC, fritzduchardt commented on internal/myks/application.go
> +}
Proposal accepted

2023-12-26 11:40 UTC, Zebradil requested changes
I propose to isolate helm-related code in `render_helm.go` as much as possible. This will make navigation through the code easier.

2023-12-26 11:40 UTC, Zebradil commented on internal/myks/application.go
> +	Enabled bool `yaml:"enabled"`
Did you mean to remove this? Somehow it survived :-)

2023-12-26 11:40 UTC, Zebradil commented on internal/myks/application.go
> +	HelmConfig       *HelmConfig
What are the benefits of carrying helm configuration everywhere with the app? Is `HelmConfig` used somewhere else apart from the helm rendering step?

2023-12-26 11:47 UTC, Zebradil commented
> dependency build would still be my preference, since it respects the Chart.lock file.

That makes sense. I only wonder if the situations when there is a lock file but dependencies aren't built are frequent.

2023-12-26 12:13 UTC, Zebradil commented on internal/myks/render_helm.go
> +	buildArgs := []string{"dependencies", "build", chartDir}
Would the following flag be useful here?

> --skip-refresh     do not refresh the local repository cache

2023-12-26 12:49 UTC, Zebradil commented
I dug a bit deeper into helm and figured out another question: in which cases we would want to prioritize dependencies in Chart.lock over dependencies in Chart.yaml?

Here is an example Chart.lock with two dependencies:

```yaml
dependencies:
- name: nginx
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 14.2.2
- name: grafana
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 9.6.5
digest: sha256:10d0bbd5014ddd04b24fa3311741326d6ddf992dff864b5a84b24bf564e3afbf
generated: "2023-12-26T13:33:52.347539414+01:00"
```

As you can see, dependencies don't carry any identification information apart from their versions. The `digest` field is used to verify that the Chart.yaml corresponds to the Chart.lock.

When I run `helm template . --dependency-update`, then change the digest manually and run `helm template . --dependency-update` again, nothing happens. When I run `helm dependency update` it detects the issue:

> Error: the lock file (Chart.lock) is out of sync with the dependencies file (Chart.yaml). Please update the dependencies

So, `helm dependency build` is helpful in such a situation, but taking one step back: I still don't see in which circumstances `--dependency-update` won't work.

2023-12-27 07:25 UTC, fritzduchardt commented
> So, `helm dependency build` is helpful in such a situation, but taking one step back: I still don't see in which circumstances `--dependency-update` won't work.

Good catch about oci registries, I should add that to the logic. Regarding the build vs update questions, have you considered that Helm also support semver wildcards?

2023-12-27 07:32 UTC, fritzduchardt commented on internal/myks/render_helm.go
> +	buildArgs := []string{"dependencies", "build", chartDir}
I was wondering about that, but think not. The tmp folder in which the registry cache resides is not getting removed between syncs. If we never update repositories it might get stale and we might fail to build new dependency versions successfully.

2023-12-27 07:37 UTC, fritzduchardt commented on internal/myks/application.go
> +	Enabled bool `yaml:"enabled"`
Crap, now it is gone for good

2023-12-27 07:38 UTC, fritzduchardt commented on internal/myks/application.go
> +	HelmConfig       *HelmConfig
What are you proposing?

2023-12-27 11:08 UTC, fritzduchardt commented on internal/myks/application.go
> +	HelmConfig       *HelmConfig
Ah, sorry, got it. To keep it as it was :)) Not sure why I moved it. Will try to revert.

2023-12-27 11:54 UTC, Zebradil commented
> Good catch about oci registries

Actually, in my tests, there was no need to add OCI registries separately. They just worked with `helm dependency build`.

> have you considered that Helm also support semver wildcards in the Chart.yaml?

I didn't, but now I've checked that as well. I see that only `helm dependency build` installs the exact version from the lock file when semver pattern is used in the main config.

But can you maybe clarify your existing case a little more? In which case you'd have a lock file but no dependencies built? What's the workflow there?

2023-12-27 12:06 UTC, Zebradil commented on internal/myks/render_helm.go
> +	buildArgs := []string{"dependencies", "build", chartDir}
~But what happens when `helm repo add` is performed? Isn't it getting the latest state of the repo already? As I can see, it is always invoked.~

I've just tested it. A repo is skipped when already exists, the index is not updated. In the worst case, we'll do refresh twice when adding the repo for the first time. This may work fine locally, but what about CI? There, repos will be added for every run and then they will be always updated immediately after that. Maybe it'd be a good solution to use `--force-update` for the `helm repo add` command and `--skip-refresh` for the `helm dependency build` command?

2023-12-27 12:07 UTC, Zebradil commented on internal/myks/application.go
> +	Enabled bool `yaml:"enabled"`
Sorry, but it seems to still be there 🙃

2023-12-27 12:08 UTC, Zebradil commented on internal/myks/environment.go
> -	log.Debug().Strs("apps", apps).Msg(e.Msg("Found rendered applications"))
Any particular reason to get rid of this log line?

2023-12-28 06:13 UTC, fritzduchardt commented on internal/myks/environment.go
> -	log.Debug().Strs("apps", apps).Msg(e.Msg("Found rendered applications"))
Crap, wish I knew

2023-12-28 06:26 UTC, fritzduchardt commented
> > Good catch about oci registries
> 
> Actually, in my tests, there was no need to add OCI registries separately. They just worked with `helm dependency build`.
> 
> > have you considered that Helm also support semver wildcards in the Chart.yaml?
> 
> I didn't, but now I've checked that as well. I see that only `helm dependency build` installs the exact version from the lock file when semver pattern is used in the main config.
> 
> But can you maybe clarify your existing case a little more? In which case you'd have a lock file but no dependencies built? What's the workflow there?

The workflow is as follows: we pull in a chart from git that is provided by another team. The chart is still in development and changes constantly. We use git instead of a helm registry, because we can create feature changes and tweak the chart. At the end we create a PR to submit the tweaks we require. This would have also have been a useful workflow for the platform components in the old days.

Thinking forward, we might want to support local charts as discussed during the last community meeting. This would require the same logic.

2023-12-28 06:33 UTC, fritzduchardt commented on internal/myks/render_helm.go
> +	buildArgs := []string{"dependencies", "build", chartDir}
Yes, sounds like a good optimization.

2023-12-28 19:01 UTC, Zebradil approved these changes
To move things forward, I reverted ArgoCD-related changes.

I'm still not sure if handling OCI registries the same way as usual HTTP registries is the best solution. As I wrote:

> Actually, in my tests, there was no need to add OCI registries separately. They just worked with helm dependency build.

But if it works, I'm fine with that.

2023-12-29 08:42 UTC, fritzduchardt commented
> To move things forward, I reverted ArgoCD-related changes.
> 
> I'm still not sure if handling OCI registries the same way as usual HTTP registries is the best solution. As I wrote:
> 
> > Actually, in my tests, there was no need to add OCI registries separately. They just worked with helm dependency build.
> 
> But if it works, I'm fine with that.

You are right. Oci registries don't require registration. I have taken them out again.

2023-12-29 08:43 UTC, fritzduchardt commented
> To move things forward, I reverted ArgoCD-related changes.

Thanks. Got lost a bit in the tangle of my open MR a while back.

2023-12-29 08:58 UTC, merged