Fix sync and vendir path structure limitation
mykso/myks pull request #172
Opened 2023-12-25 10:26 UTC by fritzduchardt

/Closes #171 
/Closes #170

2023-12-25 11:00 UTC, Zebradil commented
Please check if those issues are still present on the dev. I was fixing them yesterday.

The intricate logic is needed to precisely clean up in case of path changes. If a whole `vendor` directory is deleted, all dependencies that haven't been changed should be downloaded too.

2023-12-25 11:01 UTC, Zebradil commented on internal/integration/render_test.go
> +		}
Could you file this as a separate PR? I definitely want this part to get merged.

2023-12-25 11:05 UTC, Zebradil requested changes
Why a bunch of files in the examples directory are removed?

2023-12-25 11:05 UTC, Zebradil commented on internal/myks/sync.go
> +	if exists, _ := isExist(vendorDir); exists {
Isn't this deleting the `vendor` dir every time no matter what?

2023-12-25 11:05 UTC, Zebradil commented on internal/myks/sync.go
> +	if err := createDirectory(vendorDir); err != nil {
Creation of the `vendor` directory is also handled on line 93.

2023-12-25 11:09 UTC, fritzduchardt commented on internal/myks/sync.go
> +	if exists, _ := isExist(vendorDir); exists {
I had trouble to understand the need for the cleanup logic, but got it now. In the current implementation it should not even be required, since we don't do a sync with the --directory flag. However, since we are going back to it when fixing the vendir local directory issue, it makes sense to have it.

2023-12-25 11:11 UTC, fritzduchardt commented on internal/myks/sync.go
> +	if err := createDirectory(vendorDir); err != nil {
I started this one before noticing your fixes. Now it is a total mess. I will close this one and create separate ones for the various bits and pieces that are still valid

2023-12-25 11:20 UTC, Zebradil commented on internal/myks/sync.go
> +	if exists, _ := isExist(vendorDir); exists {
In the current implementation, it is required to handle such change in a `vendir.yaml`:

```diff
  apiVersion: vendir.k14s.io/v1alpha1
  kind: Config
  directories:
-   - path: charts/httpbingo
+   - path: charts/httpbingo-new
      contents:
        - path: .
          lazy: true
          helmChart:
            name: httpbingo
            version: 0.1.1
            repository:
              url: https://estahn.github.io/charts
```

If a directory is renamed, it won't be deleted by vendir. That's why myks has to do that.

2023-12-26 06:01 UTC, fritzduchardt commented on internal/myks/sync.go
> +	if exists, _ := isExist(vendorDir); exists {
Naturally, what was I thinking

2023-12-26 06:01 UTC, closed without merging