fix(sync): allow local paths in vendir config
mykso/myks pull request #191
Opened 2023-12-26 14:25 UTC by Zebradil

2023-12-26 23:15 UTC, Zebradil commented
This is currently not working due to a vendir bug: multiple vendir processes can't run from the same directory because they use the same `.vendir-tmp` directory.

2023-12-27 19:51 UTC, kbudde approved these changes

2023-12-27 19:53 UTC, kbudde requested changes
What's the reason of the failing test?

2023-12-28 06:48 UTC, fritzduchardt commented
> This is currently not working due to a vendir bug: multiple vendir processes can't run from the same directory because they use the same `.vendir-tmp` directory.
> 
> A solution is proposed in [carvel-dev/vendir#345](https://github.com/carvel-dev/vendir/pull/345)

Nicely done. I wonder whether this might have been the issue with struggled to reproduce when we migrated iam to myks.

2023-12-28 07:25 UTC, fritzduchardt requested changes
Looks good and does work for me. Left a minor comment about the logging. Thanks for the quick implementation. Will start using this as soon as it is out.

Out of curiosity: did the discussed solution with the vendir directory flag not work for you factually or you just liked the ytt rewrite better?

2023-12-28 07:25 UTC, fritzduchardt commented on internal/myks/sync.go
> +				log.Debug().Msgf("%s == %s", dir, path)
Can we take that one out again? For my taste syncing has become too verbose in the output log.

2023-12-28 11:43 UTC, Zebradil commented on internal/myks/sync.go
> +				log.Debug().Msgf("%s == %s", dir, path)
Yes, I'll cleanup logging there a bit. It was needed to debug the function, but when it works as expected, it is not needed.

2023-12-28 11:46 UTC, Zebradil commented
@fritzduchardt 

> did the discussed solution with the vendir directory flag not work for you factually or you just liked the ytt rewrite better?

To be honest, I forgot about this option. But anyway, it seems to me a bit hacky. With the overlay, I don't care about what's inside the vendir config, execute `vendir sync` once and do not need additional arguments.

2024-01-01 09:41 UTC, kbudde commented
@Zebradil if you merge/rebase dev (with #199), the tests should succeed.

2024-01-01 11:06 UTC, kbudde commented
Ha, renovate was so "friendly" to update vendor to the latest main commit in #200.
Therefore it's not the needed branch anymore.

2024-01-01 11:14 UTC, Zebradil commented
Strangely, I wasn't able to reproduce the issue with tests locally. But now it seems to reproduce.

2024-01-01 12:16 UTC, kbudde approved these changes

2024-01-01 12:19 UTC, merged