Draft: Refactoring to introduce an abstraction that allows for the syncing w…
mykso/myks pull request #202
Opened 2024-01-02 10:46 UTC by fritzduchardt

…ith other tools than vendir, e.g. helm dependency build. Tweaking of the log output.

2024-01-02 20:25 UTC, kbudde approved these changes
I like it 😍

2024-01-02 20:25 UTC, kbudde commented on internal/myks/globe.go
>  func (g *Globe) SyncAndRender(asyncLevel int) error {
Am I wrong or can this be simplified to 
```go
func (g *Globe) SyncAndRender(asyncLevel int) error {
	err:= g.Sync(asyncLevel)
	if err!=nil{
	  return err
	}
	return g.Render(asyncLevel)
}
```

2024-01-03 08:15 UTC, Zebradil requested changes
I left a few comments and suggestions.

YamlSyncTool should be renamed to just SyncTool, because it is not limited/specific to yaml.

Otherwise, looks good.

2024-01-03 08:15 UTC, Zebradil commented on internal/myks/sync_helm.go
> +}
Note: I think that this method can be removed from the interface completely as it is vendir-specific. But this can be done later. We also might need to repurpose it to something related to helm registry auth.

2024-01-03 08:15 UTC, Zebradil commented on internal/myks/sync_vendir.go
> +type Vendir struct {
This also should be renamed to show that it's a sync tool.

2024-01-03 08:15 UTC, Zebradil commented on internal/myks/sync_vendir.go
> +}
```suggestion
func (v Vendir) Ident() string {
	return v.ident
}
```

2024-01-03 08:44 UTC, fritzduchardt commented on internal/myks/globe.go
>  func (g *Globe) SyncAndRender(asyncLevel int) error {
No, you are correct. Good spot!

2024-01-03 08:45 UTC, fritzduchardt commented on internal/myks/sync.go
> +		log.Error().Err(err).Msg(a.Msg(yamlSyncTool.Ident(), "Failed during sync step: "+yamlSyncTool.Ident()))
So true

2024-01-03 08:45 UTC, fritzduchardt commented on internal/myks/sync_helm.go
> +type HelmRepo struct {
Done, they are both "Syncer" now

2024-01-03 08:48 UTC, fritzduchardt commented on internal/myks/sync_helm.go
> +}
I was wondering about that. But we currently execute the secret logic just once before syncing, so the method is required for that. Let's talk about this on the next meetup.

2024-01-03 08:48 UTC, fritzduchardt commented on internal/myks/sync_vendir.go
> +type Vendir struct {
It's VendirSyncer now

2024-01-03 08:48 UTC, fritzduchardt commented on internal/myks/sync_vendir.go
> +}
Good spot

2024-01-03 09:10 UTC, Zebradil commented
@fritzduchardt could you also address this:

> YamlSyncTool should be renamed to just SyncTool, because it is not limited/specific to yaml.

2024-01-04 11:37 UTC, fritzduchardt commented
> @fritzduchardt could you also address this:
> 
> > YamlSyncTool should be renamed to just SyncTool, because it is not limited/specific to yaml.

It is done - or am I missing something?

2024-01-04 12:38 UTC, Zebradil commented
@fritzduchardt you're right, sorry, probably GitHub was showing me an older changeset.

2024-01-04 12:39 UTC, Zebradil approved these changes

2024-01-04 12:41 UTC, merged