Added shell completion for apps and envs. Also, made it optional to p…
mykso/myks pull request #240
Opened 2024-02-11 10:41 UTC by fritzduchardt

…rovide to "envs/" prefix

2024-02-15 11:13 UTC, Zebradil requested changes
I left a couple of suggestions.

Otherwise, LGTM. Thanks for implementing this!

2024-02-15 11:13 UTC, Zebradil commented on internal/myks/globe.go
> +	}
This should ensure that we correctly process environment names that start with the same substring as the base dir (e.g. `envsio`, `envstarter`, etc.). 

```suggestion
	if strings.HasPrefix(envName, g.EnvironmentBaseDir+filepath.Separator) {
		return envName
	}
```

(This is not tested)

2024-02-18 08:24 UTC, fritzduchardt commented on internal/myks/globe.go
> +func (g *Globe) isEnvPath(path string) bool {
Actually, I just got triggered by a warning in my IDE: "Struct Globe has both methods on pointer and value receivers. Such usage is not recommended by Go Documentation".

2024-02-18 08:49 UTC, fritzduchardt commented
Hi @Zebradil , thanks for the review! Please have another look.

2024-02-18 10:33 UTC, Zebradil approved these changes

2024-02-18 10:34 UTC, merged