fix: helm value file merge
mykso/myks pull request #33
Opened 2023-07-07 12:39 UTC by fritzduchardt

Closes #32

2023-07-10 08:33 UTC, Zebradil commented
Thanks Fritz!

Sorry, it was a busy end of the week, I'll take a look later today.

2023-07-10 23:33 UTC, Zebradil requested changes
Good catch, I didn't have a test case for this (but I added it: https://github.com/mykso/myks/commit/53e50ba2b9e7e0e598c43ce261b9ed34703bc9c7).

Check the comment, otherwise, LGTM.

2023-07-10 23:33 UTC, Zebradil commented on internal/myks/globe.go
> +}
It doesn't make much sense to attach this function to the Globe struct, because the function is not using any data from the struct. I suggest moving this function into the `util.go` file (and adding a comment that it merges multiple yaml documents from a given file).

2023-07-12 15:33 UTC, fritzduchardt commented on internal/myks/globe.go
> +}
Good point - addressed!

@linusfr please review ;)

2023-07-16 21:01 UTC, Zebradil approved these changes

2023-07-16 21:03 UTC, merged