feat: ArgoCD support
mykso/myks pull request #41
Opened 2023-08-07 23:00 UTC by Zebradil

- chore: add yamllint configuration
- feat: add init command and a data schema file
- feat: add prototypes in the init command
- chore: build for dev with goreleaser
- feat!: merge environment manifest into env-data file
- fix: do not fail without vendir configs
- fix: data values of prototype of argocd app
- feat: add example environment configs
- refactor: use more appropriate ytt function
- feat: get git repo URL
- feat: dump configuration as ytt values
- feat: do not convert git URL protocol
- feat: add common overlays example to assets
- feat: add git branch detection and refactor data schema
- refactor: expand variable names in argocd prototype
- feat: add argocd-apps prototype
- style: sort Globe's fields alphabetically
- test: add helm values to the example httpbingo prototype
- docs: add Development section to the Readme file
- fix: helm value file merge (#33)
- feat: vendir sync caching
- feat: Add vendir sync caching
- feat: Add vendir authentication via environment
- fix: Add documentation the myks sync step (#38)
- feat: add step for rendering ytt packages (#36)
- chore: tidy go modules
- chore: formatting
- chore: use less permissive file modes
- fix: update data-schema.ytt.yaml according to the latest Myks changes
- feat: Refactoring to make log output more intelligible. (#39)
- chore: use const for a constant
- chore: remove argocd-apps prototype and supporting code
- chore: formatting
- refactor: rename vendir secret template
- refactor: extract logic into getDestinationPath func
- feat: render ArgoCD application yaml file

2023-08-17 20:21 UTC, kbudde requested changes

2023-08-17 20:21 UTC, kbudde commented on internal/myks/environment.go
> +			Enabled bool
Missing yaml struct annotations; but actually not needed to just lowercase yaml fields :) 

https://play.golang.com/p/zW7VNjuFkU-

2023-08-18 23:11 UTC, Zebradil commented on internal/myks/assets/data-schema.ytt.yaml
> +      name: in-cluster
Good catch. Applied.

2023-08-18 23:11 UTC, Zebradil commented on internal/myks/environment.go
> +			Enabled bool
I've added the anyways

2023-08-19 06:42 UTC, kbudde approved these changes

2023-08-19 06:45 UTC, kbudde commented
LGTM.

nit: your PR summary is using `_app/*/argocd` instead of `_apps/*/argocd` ;)

2023-08-19 14:25 UTC, merged