adding release name option
mykso/myks pull request #77
Opened 2023-09-08 11:44 UTC by elyesbenamor

helm will use --release-name always when templating.
- introducing new data-schema option 
`helm:
   releaseName: ""
`
-

2023-09-08 21:10 UTC, Zebradil requested changes

2023-09-08 21:10 UTC, Zebradil commented on internal/myks/assets/data-schema.ytt.yaml
> +  #! if defined, passed as the value of `--release-name` for `helm template` else default chartName wil be taken.
```suggestion
  #! if defined, passed as the value of `--release-name` for `helm template` else default chartName will be taken.
```

2023-09-08 21:10 UTC, Zebradil commented on internal/myks/render_helm.go
> +	var chartName string
Is it used?

2023-09-10 08:30 UTC, fritzduchardt requested changes
Nice new feature!

2023-09-10 08:30 UTC, fritzduchardt commented on internal/myks/render_helm.go
> +		helmCmd := []string{
Maybe there is a general error in how you try to pass the release name to `helm template` . In my understanding, the  `--release-name` flag only affects the output path (a feature not used by myks). In order to change the release name, you would have to keep the `chartName` parameter here, but replace it with `helmConfig.ReleaseName`. 

I validated my assumptions with this statement:
```
helm template my-release-name --output-dir=my-output-dir --release-name=true stable/nginx-ingress
```

2023-09-11 07:52 UTC, elyesbenamor commented on internal/myks/render_helm.go
> +	var chartName string
not, a residue that will be deleted

2023-09-11 07:56 UTC, elyesbenamor commented on internal/myks/render_helm.go
> +		helmCmd := []string{
yep it could be a solution but in my opinion if we want to use `--release-name` we can directly pass it and will be the default behavior and will replace the `ChartName`  
check lines 88-92

2023-09-11 14:49 UTC, Zebradil commented
Hey @elyesbenamor, could you describe the issue you're trying to solve more clearly? A short description of the "current" and "desired" behaviours would be helpful.

2023-09-11 14:55 UTC, Zebradil commented on internal/myks/render_helm.go
> +		helmCmd := []string{
Hey @elyesbenamor, could you describe the issue you're trying to solve more clearly? A short description of the "current" and "desired" behaviours would be helpful.

In particular, I'm not sure I completely understand why the `--release-name` flag is needed. According to helm documentation:

> `--release-name`: use release name in the output-dir path.

2023-09-13 08:32 UTC, elyesbenamor commented on internal/myks/render_helm.go
> +		helmCmd := []string{
@Zebradil sure I will explain.
So currently we have a release of vault deployed in our cluster, and argo is picking up the component using that release name. @fritzduchardt also knows this.
as the new team is taking over the vault , we will migrate the charts in our new repo and we need to overrite the release name to match the existing ones in the cluster so that argo will sync same resources in our new repo.
so using the `--release-name` option when using `helm template` will do the trick for us if it is defined , if not it will take the name of the file by default as it was

2023-09-13 10:25 UTC, Zebradil commented on internal/myks/render_helm.go
> +		helmCmd := []string{
If I understand correctly, you want to override the default release name of a helm chart during rendering, is that correct?

It doesn't seem that `--release-name` affects the rendered output:

![image](https://github.com/mykso/myks/assets/1475583/350eadd0-a0d1-4be7-85f7-896b59ee257b)

As Fritz suggested, you should use `[NAME]` for that purpose, as follows from the docs:

> `helm template [NAME] [CHART] [flags]`


Here is an example:

![image](https://github.com/mykso/myks/assets/1475583/5f97ef2b-1afe-4b8d-8395-3cdcd9de9347)

2023-09-19 08:20 UTC, closed without merging

2023-09-19 08:22 UTC, Zebradil commented
That was unexpected.

To reopen this PR the target branch has to be set to `main`. I can't change it on my own.