feature: detect additional and missing applications
mykso/myks pull request #78
Opened 2023-09-08 19:36 UTC by kbudde

smartmode: detect missing application folders
all modes: delete unconfigured applications in rendered folder. For smart only if there are other changes detected.

2023-09-10 12:00 UTC, fritzduchardt requested changes
Nice solution to finding apps that have not been rendered. The cleanup is not complete though.

2023-09-10 12:00 UTC, fritzduchardt commented on internal/myks/environment.go
> +func (e *Environment) MissingApplications() ([]string, error) {
```suggestion
// find apps that are missing from rendered folder
func (e *Environment) MissingApplications() ([]string, error) {
```

2023-09-10 12:00 UTC, fritzduchardt commented on internal/myks/environment.go
> +	files, err := os.ReadDir(dirEnvRendered)
Can we introduce a `getDestinationDir` function, just like the one we have in render.go and share it between render.go and this invocation here?

2023-09-10 12:00 UTC, fritzduchardt commented on internal/myks/environment.go
> +			err := os.RemoveAll(filepath.Join(e.g.RootDir, e.g.RenderedDir, "envs", e.Id, app))
We should also remove the argo crs in rendered/argocd/ as well as the left overs in /envs/iam-staging/_apps

2023-09-10 12:00 UTC, fritzduchardt commented on internal/myks/smart_mode.go
> +	missingApps, err := g.MissingApplications()
Adding missing apps should be done in `runSmartMode` and be mindful of whether global config has been changed, e.g. the common lib. In the case of global changes, smart mode has to rerender all applications.

2023-09-10 12:01 UTC, fritzduchardt commented on internal/myks/environment.go
> +	return missingApps, nil
Just meant as a suggestion to save lines of code. Maybe a matter of taste

2023-09-10 12:02 UTC, fritzduchardt commented on internal/myks/environment.go
> +func (e *Environment) MissingApplications() ([]string, error) {
I feel that the method name alone is not quite self-explanatory

2023-09-14 09:18 UTC, Zebradil commented
Superceeded by #89.

2023-09-14 09:18 UTC, closed without merging

2023-09-14 09:21 UTC, Zebradil commented on internal/myks/environment.go
> +func (e *Environment) MissingApplications() ([]string, error) {
Applied to #89

2023-09-14 15:56 UTC, kbudde commented
Thank you. Sorry, was a bit busy😁

2023-09-16 15:11 UTC, Zebradil commented on internal/myks/environment.go
> +			err := os.RemoveAll(filepath.Join(e.g.RootDir, e.g.RenderedDir, "envs", e.Id, app))
Removal from the `argocd` directory is implemented.

For the `_app` dir I want to collect some use cases first. We can't just delete a whole directory (e.g. `_app/nginx`), because it can contain configuration files created by a user. We could delete only `.myks`, but at the moment I do not see a good reason to do that.

2023-09-16 15:14 UTC, Zebradil commented on internal/myks/environment.go
> +	files, err := os.ReadDir(dirEnvRendered)
Yes, I'd like to do that. Not now, but as a part of a bigger refactoring. We have more magic values lying around, that are needed to be transformed into constants or configuration options.

2023-09-16 15:15 UTC, Zebradil commented on internal/myks/smart_mode.go
> +	missingApps, err := g.MissingApplications()
Implemented.

However, there is a bit of a problem with the current logic overall and I'm going to refactor the smart mode in the next PR.